# syntax=docker/dockerfile:1.7
ARG RUNTIME_IMAGE=gcr.io/distroless/base-nossl-debian13:nonroot

FROM ${RUNTIME_IMAGE}
LABEL org.opencontainers.image.licenses="Apache-2.0"
ENV LD_LIBRARY_PATH=/usr/local/lib \
    GLIBC_TUNABLES=glibc.malloc.mmap_threshold=65536
COPY --chmod=0555 --from=release-input /memeloop-token-center /usr/local/bin/memeloop-token-center
COPY --chmod=0555 --from=release-input /install-plugin-oci /usr/local/bin/install-plugin-oci
COPY --chmod=0555 --from=release-input /cosign /usr/local/bin/cosign
COPY --from=release-input /libgcc_s.so.1 /usr/local/lib/libgcc_s.so.1
COPY --from=release-input /libstdc++.so.6 /usr/local/lib/libstdc++.so.6
COPY --from=release-input /web /usr/share/memeloop-token-center/web
COPY --from=release-input /LICENSE /usr/share/licenses/memeloop-token-center/LICENSE
COPY --from=release-input /THIRD_PARTY_NOTICES.md /usr/share/licenses/memeloop-token-center/THIRD_PARTY_NOTICES.md
COPY --from=release-input /third-party-licenses /usr/share/licenses/memeloop-token-center/third-party
RUN ["/usr/local/bin/memeloop-token-center", "--help"]
RUN ["/usr/local/bin/memeloop-token-center", "verify-plugin-runtime"]
RUN ["/usr/local/bin/install-plugin-oci", "--help"]
RUN ["/usr/local/bin/install-plugin-oci", "--mtc-cosign-runtime-check"]
RUN ["/usr/local/bin/cosign", "version", "--json"]
USER 10001:10001
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/memeloop-token-center"]
CMD ["serve"]
