{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "memeloop-token-center.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "memeloop-token-center.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports: [{ protocol: TCP, port: 8080 }]
  egress:
    - {}
{{- end }}

