apiVersion: v2
name: memeloop-token-center
description: Open-source high-performance relay and usage analytics for AI text, image, and video workloads
type: application
version: 0.1.1
appVersion: "0.1.1"
annotations:
  artifacthub.io/license: Apache-2.0
