export function authorizationJourneyCopy(locale: string) {
  return locale.startsWith('zh') ? {
    purpose: '重新登录提供商，为此账号更新授权。成功后仍使用同一个账号及其模型路由；原授权将被新授权替换，账号必须与原账号一致。',
    setup: '选择提供商并登录，允许系统代表此账号调用模型。成功后会保存账号授权，供模型路由使用。',
    network: '这里保存的网络出口会立即用于此账号后续请求及登录流程，关闭表单不会撤销已保存的代理修改。请先保存或取消代理编辑，再开始登录。',
    proxyEditing: '正在编辑网络代理。请先保存或取消代理编辑，再开始登录。',
    automatic: '请在提供商页面完成登录；系统会自动检测结果，成功后返回账号页面，无需手动检查。',
    checking: '正在自动检测授权状态…',
    retrying: '暂时无法确认授权状态，系统会稍后自动重试。请勿重复开始登录。',
    startTransportFailed: '未能获取登录会话。请检查此账号的网络代理和出口连接，然后重试。',
    transportRetrying: '当前网络出口暂时无法确认授权状态。系统会自动重试；请检查代理连接，不要重复开始登录。',
    stopped: '本次授权无法继续。请返回登录设置并检查账号权限或会话有效期。',
    copyCode: '复制设备验证码',
    copied: '验证码已复制',
    copyFailed: '复制失败，请选择验证码后手动复制。',
    back: '返回上一级',
    saved: '已登录，账号授权已更新。',
  } : {
    purpose: 'Sign in to the provider again to update this account’s authorization. The same account and model routes are retained; the new authorization replaces the old one. Sign in to the original account.',
    setup: 'Choose a provider and sign in to allow the system to call models on behalf of this account. The authorization will be saved for use by model routes.',
    network: 'Saving the network connection takes effect immediately for subsequent account requests and login. Closing this form does not undo a saved proxy change. Save or cancel proxy editing before starting login.',
    proxyEditing: 'You are editing the network proxy. Save or cancel proxy editing before starting login.',
    automatic: 'Finish signing in on the provider page. The system checks automatically and returns to the account page on success; no manual check is needed.',
    checking: 'Checking authorization automatically…',
    retrying: 'Authorization could not be confirmed yet. The system will retry automatically. Do not start another login.',
    startTransportFailed: 'Could not obtain a login session. Check this account’s proxy and egress, then retry.',
    transportRetrying: 'The current network connection cannot confirm authorization yet. The system will retry automatically; check the proxy connection and do not start another login.',
    stopped: 'This authorization cannot continue. Return to login setup and check account permissions or session expiry.',
    copyCode: 'Copy device code',
    copied: 'Device code copied',
    copyFailed: 'Copy failed. Select the device code and copy it manually.',
    back: 'Back to previous page',
    saved: 'Signed in. Account authorization updated.',
  };
}
