export function authorizationJourneyCopy(locale: string, providerId?: string) {
  return locale.startsWith('zh') ? {
    purpose: '重新登录提供商以更新此连接的授权。连接名称和模型路由保持不变；原授权将被新授权替换。',
    identityHelp: providerId === 'kimi-oauth'
      ? '请在 Kimi 页面核对登录账号。Kimi 不向此页面提供账号身份；下方连接名称只是你为连接设置的名称，不代表已核验的 Kimi 账号。'
      : providerId === 'anthropic-claude' ? '请使用原 Anthropic 账号登录；系统要求重新授权的身份与原账号一致。'
      : providerId === 'google-antigravity' ? '请使用原 Google 身份登录；系统要求重新授权的身份与原账号一致。' : '',
    setup: '选择提供商并登录，允许系统代表此账号调用模型。成功后会保存账号授权，供模型路由使用。',
    network: '这里保存的网络出口会立即用于此账号后续请求及登录流程，关闭表单不会撤销已保存的代理修改。请先保存或取消代理编辑，再开始登录。',
    proxyEditing: '正在编辑网络代理。请先保存或取消代理编辑，再开始登录。',
    automatic: '请在提供商页面完成登录；系统会自动检测结果并保存连接，无需手动检查。',
    checking: '正在自动检测授权状态…',
    retrying: '暂时无法确认授权状态，系统会稍后自动重试。请勿重复开始登录。',
    startTransportFailed: '未能获取登录会话。请检查此账号的网络代理和出口连接，然后重试。',
    transportRetrying: '当前网络出口暂时无法确认授权状态。系统会自动重试；请检查代理连接，不要重复开始登录。',
    stopped: '本次授权无法继续。请返回登录设置并检查账号权限或会话有效期。',
    completeInvalidSession: '此次登录会话无效。请关闭授权表单，检查账号状态；如仍需授权，重新打开表单并开始登录。',
    completeExpired: '此次登录会话已过期。请关闭授权表单，检查账号状态；如仍需授权，重新打开表单并开始登录。',
    completeInactive: '此次登录会话已不可用。请关闭授权表单，检查账号状态；如仍需授权，重新打开表单并开始登录。',
    completeInvalidCode: '授权码格式不正确。请从本次提供商登录页面重新复制完整的授权结果（包含 # 分隔符），再提交。',
    completeStateMismatch: '授权结果与本次登录会话不匹配。请从本次提供商登录页面重新复制完整的授权结果；若已无法获取，请关闭并重新打开授权表单开始登录。',
    completeIdentityMismatch: '登录的 Anthropic 账号与原账号不同。请关闭并重新打开授权表单，使用原 Anthropic 账号重新登录。',
    completeUnauthorized: '当前管理凭据已失效或未被接受。请重新登录管理台，检查账号状态后再决定是否重新授权。',
    completeForbidden: '当前身份无权完成此次授权。请检查账号所属租户和操作权限，必要时联系管理员；确认后关闭并重新打开授权表单。',
    completeUnavailable: '提供商暂时无法完成授权。请关闭表单，先检查账号状态及代理连接；如仍需授权，重新打开表单后重试。',
    completeOverloaded: '服务繁忙，暂时无法确认授权结果。请关闭表单并检查账号状态；如仍需授权，稍后重新打开表单重试。',
    completeUncertain: '授权结果暂时无法确认。请关闭表单并检查账号状态；如仍需授权，重新打开表单后重试或重新开始登录。',
    completeClosedUnknown: '关闭表单时，已发出的授权确认请求尚未返回结果，自动查询已停止。浏览器停止等待不代表服务端已取消处理。会话与授权码已保留；请先检查账号状态，再决定是否手动重试。',
    completePending: '授权仍在处理中，尚未确认成功。系统会按服务端要求的间隔自动查询；请勿重复开始登录。',
    completeChecking: '正在确认此次授权结果…',
    completeLimited: '本次自动确认已达到等待时限或次数上限，结果仍未确认。会话与授权码已保留；请先检查账号状态，如仍需登录，再返回登录设置。',
    copyCode: '复制设备验证码',
    copied: '验证码已复制',
    copyFailed: '复制失败，请选择验证码后手动复制。',
    back: '返回上一级',
    saved: '已登录，账号授权已更新。',
  } : {
    purpose: 'Sign in to the provider again to update this connection’s authorization. Its connection name and model routes are retained; the new authorization replaces the old one.',
    identityHelp: providerId === 'kimi-oauth'
      ? 'Check the login account on the Kimi page. Kimi does not provide an account identity to this page. The connection name below is your label for this connection, not a verified Kimi account.'
      : providerId === 'anthropic-claude' ? 'Sign in with the original Anthropic account. Reauthorization requires the same provider identity.'
      : providerId === 'google-antigravity' ? 'Sign in with the original Google identity. Reauthorization requires the same provider identity.' : '',
    setup: 'Choose a provider and sign in to allow the system to call models on behalf of this account. The authorization will be saved for use by model routes.',
    network: 'Saving the network connection takes effect immediately for subsequent account requests and login. Closing this form does not undo a saved proxy change. Save or cancel proxy editing before starting login.',
    proxyEditing: 'You are editing the network proxy. Save or cancel proxy editing before starting login.',
    automatic: 'Finish signing in on the provider page. The system checks automatically and saves the connection; no manual check is needed.',
    checking: 'Checking authorization automatically…',
    retrying: 'Authorization could not be confirmed yet. The system will retry automatically. Do not start another login.',
    startTransportFailed: 'Could not obtain a login session. Check this account’s proxy and egress, then retry.',
    transportRetrying: 'The current network connection cannot confirm authorization yet. The system will retry automatically; check the proxy connection and do not start another login.',
    stopped: 'This authorization cannot continue. Return to login setup and check account permissions or session expiry.',
    completeInvalidSession: 'This login session is invalid. Close the authorization form and check the account status; if authorization is still needed, reopen the form and start login again.',
    completeExpired: 'This login session has expired. Close the authorization form and check the account status; if authorization is still needed, reopen the form and start login again.',
    completeInactive: 'This login session is no longer available. Close the authorization form and check the account status; if authorization is still needed, reopen the form and start login again.',
    completeInvalidCode: 'The authorization code format is incorrect. Copy the complete authorization result, including the # separator, from this provider login and submit it again.',
    completeStateMismatch: 'The authorization result does not match this login session. Copy the complete result from this provider login again; if it is no longer available, close and reopen the authorization form to start login again.',
    completeIdentityMismatch: 'The signed-in Anthropic account differs from the original account. Close and reopen the authorization form, then sign in with the original Anthropic account.',
    completeUnauthorized: 'Your management credential has expired or was not accepted. Sign in to the console again and check the account status before deciding whether to reauthorize.',
    completeForbidden: 'Your current identity cannot complete this authorization. Check the account tenant and your permissions, or contact an administrator; once confirmed, close and reopen the authorization form.',
    completeUnavailable: 'The provider cannot complete authorization right now. Close the form and check the account status and proxy connection; if authorization is still needed, reopen the form to retry.',
    completeOverloaded: 'The service is busy and the authorization result cannot be confirmed yet. Close the form and check the account status; if authorization is still needed, reopen the form to retry later.',
    completeUncertain: 'The authorization result cannot be confirmed yet. Close the form and check the account status; if authorization is still needed, reopen the form to retry or start login again.',
    completeClosedUnknown: 'The authorization confirmation request was still awaiting a result when you closed the form. Automatic checks have stopped. Stopping the browser wait does not mean the server cancelled processing. The session and authorization code are retained. Check the account status before deciding whether to retry manually.',
    completePending: 'Authorization is still processing and success is not confirmed. Checks will continue at the interval requested by the server. Do not start another login.',
    completeChecking: 'Confirming this authorization result…',
    completeLimited: 'This confirmation reached its time or attempt limit without a confirmed result. The session and authorization code are retained. Check the account status before returning to login setup if login is still needed.',
    copyCode: 'Copy device code',
    copied: 'Device code copied',
    copyFailed: 'Copy failed. Select the device code and copy it manually.',
    back: 'Back to previous page',
    saved: 'Signed in. Account authorization updated.',
  };
}
