export function authorizationCodeCopy(locale: string) {
  return locale.startsWith('zh') ? {
    help: '使用部署提供的登录客户端，无需自行创建 Google OAuth 项目。配置仅在当前页面内保留；离开页面会清除登录草稿。',
    admin: '管理员尚未正确配置此提供商的默认 OAuth 客户端。请在部署 Secret MTC_PROVIDER_OAUTH_CLIENT_DEFAULTS_JSON 中配置后重试。',
    forbidden: '此登录流程目前仅允许全局管理员操作。请联系管理员。',
    failed: '登录请求未完成。草稿已保留；请检查配置后手动重试。',
    uncertain: '尚未确认账号是否创建成功。不会自动重新兑换授权码；请先检查上游账号列表，再决定是否重新登录。',
    pending: '服务器仍在处理登录。不会自动重发；请稍后检查账号列表。',
    reauthorize: '此流程暂不支持原账号重新授权；请勿用新建登录代替，以免创建重复账号。',
    network: '登录网络', direct: '直接连接', proxy: '使用代理', proxyScope: '代理网络范围', public: '公网', private: '私网',
    callback: '完整回调地址', callbackHelp: '在新标签页完成登录后，复制地址栏中的完整回调 URL（包含 code 和 state）。即使本机回调页无法打开，也请复制地址栏。不要粘贴到聊天或工单。',
    invalid: '请输入包含 code 和 state 的完整 HTTP 或 HTTPS 回调地址。',
    waiting: '等待你在提供商页面完成登录', expires: '首次提交授权码截止时间', config: '提供商连接配置', reset: '清除登录草稿',
    recoveryExpires: '已签发登录结果的恢复截止时间',
    recoveryHint: '恢复期限仅适用于服务器已经签发并保存的登录结果，不延长首次授权码兑换期限。处理中或结果未知时请保留此页面，先检查账号列表；不会自动重新兑换授权码。',
    continueSetup: '继续完成接入',
    continueHelp: '仅继续处理服务器已签发的登录结果，不发送授权码，不发起新的登录。',
    continueFailed: '暂时无法继续完成接入。请先检查账号列表；本次未发送授权码。你可以稍后在截止时间前手动继续。',
    continueExpired: '已超过已签发登录结果的恢复期限。请先检查账号列表，再决定是否开始新的登录。',
    abandon: '清除当前登录草稿？此操作不会撤销提供商已授予的授权，也不会删除已创建的账号。',
    check: '检查账号列表', saved: '账号已创建；可在上游列表查看状态和代理配置。',
    savedButReadFailed: '账号已保存，但暂时无法刷新账号列表。请重试读取列表，无需重新登录或再次提交授权码。',
  } : {
    help: 'Use the deployment-provided login client; no Google OAuth project setup is required. Drafts stay only on this page and are cleared when you leave.',
    admin: 'The default OAuth client for this provider is missing or invalid. Ask an administrator to configure deployment Secret MTC_PROVIDER_OAUTH_CLIENT_DEFAULTS_JSON.',
    forbidden: 'This login flow currently requires a global administrator. Contact your administrator.',
    failed: 'Login could not start. Your draft is preserved; check the configuration before retrying manually.',
    uncertain: 'Account creation is not confirmed. The authorization code will not be exchanged again automatically. Check the upstream account list before starting another login.',
    pending: 'The server is still processing login. No request will be resent automatically; check the account list shortly.',
    reauthorize: 'This flow does not yet support reauthorizing an existing account. Starting a new login could create a duplicate account.',
    network: 'Login network', direct: 'Direct connection', proxy: 'Use a proxy', proxyScope: 'Proxy network scope', public: 'Public', private: 'Private',
    callback: 'Complete callback URL', callbackHelp: 'After signing in in the new tab, copy the complete callback URL from its address bar, including code and state. Copy it even if the local callback page cannot open. Do not paste it into chats or support tickets.',
    invalid: 'Enter a complete HTTP or HTTPS callback URL containing code and state.',
    waiting: 'Waiting for you to sign in with the provider', expires: 'First authorization-code submission deadline', config: 'Provider connection settings', reset: 'Clear login draft',
    recoveryExpires: 'Issued login result recovery deadline',
    recoveryHint: 'Recovery applies only to login results already issued and saved by the server; it does not extend the initial code-exchange deadline. Keep this page open for pending or uncertain outcomes and check the account list first. Codes are never exchanged again automatically.',
    continueSetup: 'Continue account setup',
    continueHelp: 'Continue processing only a login result already issued by the server. No authorization code is sent and no new login is started.',
    continueFailed: 'Account setup could not continue yet. Check the account list first; no authorization code was sent. You can continue manually before the deadline.',
    continueExpired: 'The issued login result recovery deadline has passed. Check the account list before deciding whether to start a new login.',
    abandon: 'Clear this login draft? This does not revoke provider authorization or delete an account already created.',
    check: 'Check account list', saved: 'Account created. View its status and proxy settings in the upstream list.',
    savedButReadFailed: 'The account is saved, but the account list could not refresh. Retry reading the list; do not sign in again or resubmit the authorization code.',
  };
}
