// Page orchestration copy lives alongside the composition, not in schema data.
export function formJourneyCopy(locale: string) {
  return locale.startsWith('zh') ? {
    authentication: '认证凭据', authenticationHint: '仅填写所选提供商需要的凭据。网络代理与 API 地址分开配置。',
    advancedAuthentication: '自定义认证请求头', advancedAuthenticationHint: '仅在提供商要求自定义请求头名称或凭据前缀时修改；否则保留默认值。',
    authenticationHeaderHint: '填写提供商指定的 HTTP 请求头名称，例如 authorization 或 x-api-key。', authenticationPrefixHint: '填写凭据前的文字，包含所需空格，例如 Bearer 后的空格；不需要前缀时留空。',
    timeouts: '配置超时与重试', timeoutsHint: '设置连接、读取和故障切换的等待时限。只修改代理地址时，无需调整这些设置。',
    advancedConnection: '高级网络与用量设置', advancedConnectionHint: '按需配置网络访问范围、额度预留及提供商专用选项；不确定时保持原值。',
    identity: '身份与归属', policy: '用量与预算', policyHint: '先选择计费方式；只有需要限制用量时再设置预算。',
    budget: '可选用量限制', budgetHint: '保持原有默认值表示沿用当前策略；展开后可调整具体限制。',
    candidates: '按上游组选择与排除', candidatesHint: '直接选择账号即可开始。需要动态管理候选账号时，再配置上游组；排除优先。',
    priority: '路由优先级', preview: '配置预览', noModel: '尚未选择模型', noUpstream: '尚未选择上游',
    access: '凭据授权', noGrant: '未新增凭据授权；不会自动向所有凭据开放。',
    codexProxy: '此地址用于标识服务协议端点。可为账号配置独立的 socks5h 网络代理；留空时使用服务端默认出口。',
    draftNoRoutes: '尚未授权模型访问；可创建后再配置路由。',
    credentialFlowHint: '填写使用者，选择可访问的模型，再按需设置预算。',
    concurrentDraftPreserved: '配置已被其他人修改。你的草稿已保留；请关闭并重新打开编辑，查看最新配置后重试。',
    routeAccess: '3. 模型访问授权', protocolHelp: '协议兼容性说明',
  } : {
    authentication: 'Authentication', authenticationHint: 'Use credentials for the selected provider. Configure the network proxy separately from the API endpoint.',
    advancedAuthentication: 'Custom authentication headers', advancedAuthenticationHint: 'Change the header name or credential prefix only when required by your provider. Otherwise keep the defaults.',
    authenticationHeaderHint: 'Enter the HTTP header name required by your provider, such as authorization or x-api-key.', authenticationPrefixHint: 'Enter any text before the credential, including required spaces such as the space after Bearer. Leave empty when no prefix is needed.',
    timeouts: 'Configure timeouts and retries', timeoutsHint: 'Set how long to wait for connections, responses and failover. Leave these unchanged when only updating the proxy address.',
    advancedConnection: 'Advanced network and usage settings', advancedConnectionHint: 'Configure network access, credit reservations and provider-specific options as needed. Keep the current values if unsure.',
    identity: 'Identity and ownership', policy: 'Usage and budget', policyHint: 'Choose billing behavior first; add budgets only when you need usage limits.',
    budget: 'Optional usage limits', budgetHint: 'Unchanged values retain the current policy. Expand to adjust individual limits.',
    candidates: 'Include or exclude upstream groups', candidatesHint: 'Select accounts to start. Use groups for a dynamic candidate set; exclusions take precedence.',
    priority: 'Routing priority', preview: 'Configuration preview', noModel: 'No model selected', noUpstream: 'No upstream selected',
    access: 'Credential access', noGrant: 'No new credential grants; this does not automatically grant access to every credential.',
    codexProxy: 'This is the service protocol endpoint. Add a dedicated socks5h account proxy when needed, or use the server default egress.',
    draftNoRoutes: 'No model access selected. You can configure routes after creation.',
    credentialFlowHint: 'Name the user, choose model access, then set a budget if needed.',
    concurrentDraftPreserved: 'Someone changed this configuration. Your draft is preserved; close and reopen the editor to review the latest version before retrying.',
    routeAccess: '3. Model access', protocolHelp: 'Protocol compatibility details',
  };
}
