export function providerConnectionCopy(locale: string) {
  return locale.startsWith('zh') ? {
    identity: '账号', network: '网络与连接', authentication: '认证', routing: '路由设置',
    displayName: '备注名称',
    editDisplayName: '修改名称',
    signInAgain: '重新登录',
    authorizationExpires: '授权有效期',
    authorizationExpiryUnknown: '未知',
    renameResponseUncertain: '无法确认名称是否已保存。请重新读取账号列表后核对。',
    providerIdentity: '登录账号',
    kimiIdentityUnavailable: '未获取',
    readFailed: '无法读取当前代理地址。请重新打开编辑；若仍失败，请确认管理权限。',
    noProxy: '未配置网络代理', copyProxy: '复制代理地址', copyEndpoint: '复制服务地址',
    viewProxy: '查看代理地址', hideProxy: '隐藏代理地址',
    routingHint: '模型路由在模型管理中配置；这里的连接设置对该账号的所有路由生效。',
    openRoutes: '管理模型路由', discard: '当前修改尚未保存。放弃修改并继续？',
  } : {
    identity: 'Account', network: 'Network and connection', authentication: 'Authentication', routing: 'Routing settings',
    displayName: 'Display name',
    editDisplayName: 'Rename',
    signInAgain: 'Sign in again',
    authorizationExpires: 'Authorization expires',
    authorizationExpiryUnknown: 'Unknown',
    renameResponseUncertain: 'The saved name could not be confirmed. Reload the account list to check it.',
    providerIdentity: 'Sign-in account',
    kimiIdentityUnavailable: 'Unavailable',
    readFailed: 'Cannot read the current proxy address. Reopen the editor; if this persists, check management permissions.',
    noProxy: 'No network proxy configured', copyProxy: 'Copy proxy address', copyEndpoint: 'Copy service address',
    viewProxy: 'Show proxy address', hideProxy: 'Hide proxy address',
    routingHint: 'Configure model routes in Models. These connection settings apply to every route using this account.',
    openRoutes: 'Manage model routes', discard: 'Your changes have not been saved. Discard them and continue?',
  };
}
