export function transportProxyGroupCopy(locale: string) {
  return locale.startsWith('zh') ? {
    title: '代理组', manage: '管理代理组', chooseGroup: '选择代理组',
    purpose: '为账号设置多个备用网络出口。系统优先沿用当前出口，无法建立连接时再尝试其他出口。',
    selectTenant: '请先选择要管理的租户。', checking: '正在加载代理组入口…',
    denied: '你没有管理代理组的权限，请联系管理员开通。',
    unavailable: '暂时无法打开代理组，请重试。', retry: '重试',
    groupsHint: '每组可添加1–4个网络出口。删除正在使用的组前，请先更改对应账号的设置。',
    bindingTitle: '账号使用的代理组',
    bindingHint: '选择Codex订阅账号、代理组和首次使用的出口。再次保存同一组不会切换当前出口。',
    closePending: '保存结果尚未确认。关闭不会取消保存，请再次打开后核对结果，避免重复提交。仍要关闭吗？',
    closeDraft: '代理组修改尚未保存。放弃修改并关闭？',
    refreshDraft: '刷新会丢弃尚未保存的修改。继续刷新？',
    refreshedUnknown: '配置已刷新。请核对上次修改是否已保存，再决定是否重新提交。',
    accountRefreshFailed: '配置已提交，但账号列表未能刷新。请关闭后刷新列表。',
    bound: '账号代理组已保存，正在应用新的连接设置。',
    unbound: '已解除代理组绑定，账号将继续使用所选出口，不会改为直连。',
    refresh: '刷新配置', connectionDetails: '连接状态详情', observedAt: '状态更新时间', observedExit: '当前节点选择的出口',
    refreshRequired: '出口信息已变化，请刷新', noSelection: '尚未选择出口',
    runtimeHint: '这是当前响应节点的状态，其他节点可能尚未更新。配置已加载不代表代理连接已验证。',
    runtime: { unbound: '未使用代理组', pending: '连接设置正在更新', applied: '当前节点已加载连接设置', unavailable: '暂时无法读取连接状态' },
    operationStatus: '代理组操作结果', empty: '还没有代理组。新建一个组，为账号添加备用出口。',
    groupSummary: (name: string, members: number, accounts: number) => `${name} · ${members}个出口 · ${accounts}个账号`,
    edit: (name: string) => `编辑 ${name}`, confirmDelete: (name: string) => `删除代理组“${name}”？`,
    deleted: '代理组已删除。', create: '新建代理组', name: '代理组名称',
    candidate: (index: number) => `网络出口 ${index}`, memberName: '出口名称',
    replaceAddress: '替换代理地址（留空保留原值）', requiredAddress: '私网代理地址（必填）', address: '私网代理地址',
    removeMember: '移除出口', addressHint: '使用私网或集群内服务的socks5h地址，不要重复添加。地址保存后不会再次显示。',
    addMember: '添加出口', replacement: '移除当前出口后使用', selectSavedMember: '请选择已保存的备用出口', unnamed: '未命名出口',
    replacementHint: '若要换成新出口，请先添加并保存，再移除旧出口。', save: '保存代理组', cancelEdit: '取消编辑',
    discardEdit: '放弃尚未保存的代理组修改？', saved: '代理组配置已保存。',
    account: '账号', selectAccount: '请选择账号', noAccounts: '当前租户没有可设置代理组的Codex订阅账号。',
    loadingBinding: '正在加载账号的代理设置…', currentGroup: '当前代理组', noGroup: '未使用代理组',
    selectGroup: '请选择代理组', targetGroup: '目标代理组', initialExit: '起始出口', selectExit: '请选择起始出口',
    saveBinding: '保存账号绑定', retainedExit: '解绑后保留的单代理出口', selectRetained: '请选择保留出口',
    unlink: '解绑并保留所选代理', confirmUnlink: '解除代理组绑定？账号将继续使用所选出口，不会改为直连。',
    errors: {
      unknown: '保存结果尚未确认，关闭页面也不会取消保存。请刷新配置，核对修改是否已保存后再重试。',
      load: '无法加载代理配置，请重试。',
      groupConflict: '代理组已被其他操作更新。请刷新配置后重新修改。',
      bindingConflict: '账号的连接设置已变化。请刷新配置后重新选择。',
      inUse: '代理组仍在使用中。请先更改相关账号的代理组或解除绑定，再删除此组。',
      capacity: '代理组或绑定数量已达上限，请联系管理员清理不再使用的配置。',
      invalid: '配置无效。请检查名称、出口数量和私网socks5h地址。替代出口须先添加并保存。',
      denied: '你没有管理代理组的权限，或登录凭据已失效。请联系管理员检查访问权限。',
      validation: '部分配置填写有误，修改已保留。请检查输入后重新保存。',
      missing: '账号或代理组已不存在，请刷新配置。',
      conflict: '配置已变化，请刷新后重新修改。',
    },
  } : {
    title: 'Proxy groups', manage: 'Manage proxy groups', chooseGroup: 'Choose proxy group',
    purpose: 'Give an account backup network exits. The current exit stays selected; another is tried only when a connection cannot be established.',
    selectTenant: 'Select the tenant you want to manage.', checking: 'Loading proxy group access…',
    denied: 'You do not have permission to manage proxy groups. Contact an administrator.',
    unavailable: 'Proxy groups cannot be opened right now. Try again.', retry: 'Retry',
    groupsHint: 'Add 1–4 network exits per group. Before deleting a group in use, change the settings of its accounts.',
    bindingTitle: 'Account proxy group',
    bindingHint: 'Choose a Codex subscription account, a group and its initial exit. Saving the same group again does not switch the current exit.',
    closePending: 'The save result is not yet confirmed. Closing does not cancel the save. Reopen and check before submitting again. Close anyway?',
    closeDraft: 'Your proxy group changes are not saved. Discard them and close?',
    refreshDraft: 'Refreshing will discard your unsaved changes. Continue?',
    refreshedUnknown: 'Configuration refreshed. Check whether your previous changes were saved before submitting again.',
    accountRefreshFailed: 'Configuration submitted, but the account list could not refresh. Close and refresh the list.',
    bound: 'Account proxy group saved. The new connection settings are being applied.',
    unbound: 'Proxy group unlinked. The account will keep the selected exit and will not connect directly.',
    refresh: 'Refresh configuration', connectionDetails: 'Connection details', observedAt: 'Status updated', observedExit: 'Exit selected by this node',
    refreshRequired: 'Exit information changed. Refresh to update it.', noSelection: 'No exit selected yet',
    runtimeHint: 'This is the responding node’s status; other nodes may still be updating. Loaded settings do not confirm a working proxy connection.',
    runtime: { unbound: 'No proxy group in use', pending: 'Updating connection settings', applied: 'This node loaded the connection settings', unavailable: 'Connection status is temporarily unavailable' },
    operationStatus: 'Proxy group action result', empty: 'No proxy groups yet. Create one to give an account backup exits.',
    groupSummary: (name: string, members: number, accounts: number) => `${name} · ${members} ${members === 1 ? 'exit' : 'exits'} · ${accounts} ${accounts === 1 ? 'account' : 'accounts'}`,
    edit: (name: string) => `Edit ${name}`, confirmDelete: (name: string) => `Delete proxy group “${name}”?`,
    deleted: 'Proxy group deleted.', create: 'Create proxy group', name: 'Proxy group name',
    candidate: (index: number) => `Network exit ${index}`, memberName: 'Exit name',
    replaceAddress: 'Replacement proxy address (leave blank to keep it)', requiredAddress: 'Private proxy address (required)', address: 'Private proxy address',
    removeMember: 'Remove exit', addressHint: 'Use a private or in-cluster socks5h address, without duplicates. Saved addresses are not shown again.',
    addMember: 'Add exit', replacement: 'Exit to use after removing the current one', selectSavedMember: 'Choose a saved backup exit', unnamed: 'Unnamed exit',
    replacementHint: 'To use a new exit, add and save it before removing the old one.', save: 'Save proxy group', cancelEdit: 'Cancel editing',
    discardEdit: 'Discard unsaved proxy group changes?', saved: 'Proxy group configuration saved.',
    account: 'Account', selectAccount: 'Choose an account', noAccounts: 'This tenant has no Codex subscription accounts that can use proxy groups.',
    loadingBinding: 'Loading the account’s proxy settings…', currentGroup: 'Current proxy group', noGroup: 'No proxy group',
    selectGroup: 'Choose a proxy group', targetGroup: 'Target proxy group', initialExit: 'Initial exit', selectExit: 'Choose the initial exit',
    saveBinding: 'Save account binding', retainedExit: 'Single proxy exit to keep after unlinking', selectRetained: 'Choose an exit to keep',
    unlink: 'Unlink and keep selected proxy', confirmUnlink: 'Unlink the proxy group? The account will keep the selected exit and will not connect directly.',
    errors: {
      unknown: 'The save result is not confirmed. Closing the page does not cancel the save. Refresh and check whether your changes were saved before retrying.',
      load: 'Proxy settings could not be loaded. Try again.',
      groupConflict: 'The proxy group was changed elsewhere. Refresh before editing again.',
      bindingConflict: 'The account’s connection settings changed. Refresh and select your settings again.',
      inUse: 'This proxy group is still in use. Change or unlink its accounts before deleting it.',
      capacity: 'The group or binding limit has been reached. Ask an administrator to remove unused settings.',
      invalid: 'Check the name, number of exits and private socks5h addresses. Add and save a replacement exit before selecting it.',
      denied: 'Your access has expired or does not allow proxy group management. Ask an administrator to check your access.',
      validation: 'Some settings are invalid. Your changes are kept; check the inputs and save again.',
      missing: 'The account or proxy group no longer exists. Refresh the configuration.',
      conflict: 'The configuration changed. Refresh before editing again.',
    },
  };
}
