export function upstreamNotesCopy(locale: string) {
  return locale.startsWith('zh') ? {
    title: '备注',
    description: '记录该上游账号的官网、API 文档等参考链接，支持 Markdown 格式。备注仅供查看，不影响 API 地址、连接或模型路由设置。',
    edit: '编辑',
    preview: '预览',
    modeLabel: '切换编辑或预览',
    toolbarLabel: '插入格式',
    bold: '加粗',
    italic: '斜体',
    link: '链接',
    bulletList: '列表',
    boldPlaceholder: '加粗文字',
    italicPlaceholder: '斜体文字',
    linkPlaceholder: '链接文字',
    listPlaceholder: '列表项',
    placeholder: '例如：官网 https://example.com\nAPI 文档 https://example.com/docs',
    formatHint: '支持 **加粗**、*斜体*、`代码`、[链接](https://…)、# 标题和 - 列表；仅 http/https 链接可点击，图片只显示为链接文字。',
    empty: '暂无备注。',
    save: '保存备注',
    saving: '正在保存…',
    cancel: '取消',
    saved: '备注已保存。',
    saveUnconfirmed: '无法确认备注是否已保存。请重新打开账号后核对。',
    stale: '该账号刚被其他操作更新。请关闭后重新打开编辑，再修改备注。',
    tooLong: '备注过长：最多 16,384 个字符，且编码后不超过 64 KB。请精简后再保存。',
    controlChars: '备注包含不支持的控制字符。请删除从其他程序粘贴的不可见字符后再保存。',
  } : {
    title: 'Notes',
    description: 'Keep reference links such as the provider website and API documentation for this upstream account. Markdown is supported. Notes are for reading only and do not affect the API address, connection, or model routing settings.',
    edit: 'Edit',
    preview: 'Preview',
    modeLabel: 'Switch between editing and preview',
    toolbarLabel: 'Insert formatting',
    bold: 'Bold',
    italic: 'Italic',
    link: 'Link',
    bulletList: 'List',
    boldPlaceholder: 'bold text',
    italicPlaceholder: 'italic text',
    linkPlaceholder: 'link text',
    listPlaceholder: 'list item',
    placeholder: 'For example: Website https://example.com\nAPI docs https://example.com/docs',
    formatHint: 'Supports **bold**, *italic*, `code`, [links](https://…), # headings and - lists. Only http/https links are clickable; images show as link text.',
    empty: 'No notes yet.',
    save: 'Save notes',
    saving: 'Saving…',
    cancel: 'Cancel',
    saved: 'Notes saved.',
    saveUnconfirmed: 'Could not confirm whether the notes were saved. Reopen the account to check.',
    stale: 'This account was just updated elsewhere. Close and reopen it before editing the notes again.',
    tooLong: 'The notes are too long: at most 16,384 characters and 64 KB when encoded. Shorten them before saving.',
    controlChars: 'The notes contain unsupported control characters. Remove invisible characters pasted from other programs before saving.',
  };
}
